---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-second
  name: nginx-second
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: nginx-second
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-second
  name: nginx-second
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      run: nginx-second
  template:
    metadata:
      labels:
        run: nginx-second
    spec:
      volumes:
        - name: webdata
          emptyDir: {}
      initContainers:
        - name: web-content
          image: busybox
          volumeMounts:
            - name: webdata
              mountPath: "/webdata"
          ports:
            - containerPort: 80
          command: [
              "/bin/sh",
              "-c",
              'echo "<!DOCTYPE html>
              <html>
              <head>
              <title>Hello there again!</title>
              <style>
              body {
              width: 35em;
              margin: 0 auto;
              font-family: Tahoma, Verdana, Arial, sans-serif;
              }
              </style>
              </head>
              <body>
              <h1>Hello there!</h1>
              <p>If you see this page, that means aws eks is up.</p>" > /webdata/index.html',
            ]
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - name: webdata
              mountPath: "/usr/share/nginx/html"




---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: nginx
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
        - name: webdata
          emptyDir: {}
      initContainers:
        - name: web-content
          image: busybox
          volumeMounts:
            - name: webdata
              mountPath: "/webdata"
          ports:
            - containerPort: 80
          command: [
              "/bin/sh",
              "-c",
              'echo "<!DOCTYPE html>
              <html>
              <head>
              <title>Hello there!</title>
              <style>
              body {
              width: 35em;
              margin: 0 auto;
              font-family: Tahoma, Verdana, Arial, sans-serif;
              }
              </style>
              </head>
              <body>
              <h1>Hello there!</h1>
              <p>If you see this page, that means things are working :).</p>" > /webdata/index.html',
            ]
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - name: webdata
              mountPath: "/usr/share/nginx/html"
---

